---
- name: Create/Delete/Update alert notifications channels (provisioning)
  become: true
  ansible.builtin.copy:
    content: |
      apiVersion: 1
      {{ grafana_alert_notifications | to_nice_yaml }}
    dest: /etc/grafana/provisioning/notifiers/ansible.yml
    owner: root
    group: grafana
    mode: "a+rwx,u-x,g-wx,o-rwx,ug-s"
  notify: restart grafana
  when: grafana_use_provisioning
